org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
revenuecatPublicKey=test_oNyHNqdgxSKRTGRbrpbWcFnNhnp
firebaseApiKey=AIzaSyDc3SYdWCS8Sl5KnAxBXRYV31VnZXAOBc0
firebaseAppId=1:1026667048908:android:512320a5025a0e8dbfb769
firebaseProjectId=uni-reminder-1255e
backendUrl=https://ship-a-thon.onrender.com
